version: '3'

volumes:
  samba_data:
    driver: local
  samba_private_data:
    driver: local

services:
  samba-dc:
    image: akira345/samba4-ad:latest
    volumes:
      #- /etc/localtime:/etc/localtime:ro # Windows以外は指定しないと時刻がズレて認証が通らなくなる
      - samba_data:/usr/local/samba/var              #ログインスクリプトなどが入っているっぽい。パーミッションを見ているようなのでローカルマウント不可
      - samba_private_data:/usr/local/samba/private  #証明書とかLDAP情報が格納される。パーミッションを見ているようなのでローカルマウント不可
      - ./samba/config:/usr/local/samba/external     #この設定ファイルを削除すると作り変えるので注意。
    environment:
      - DOMAIN=example.com        #ドメイン名
      - DOMAINPASS=Pass1234       #administratorのパスワード。.envファイルに切り出すなどしたほうが良い。
      - HOSTIP=192.168.0.15       #DockerサーバのIPアドレス。以下同様
      - DNSFORWARDER=8.8.8.8      #ADドメイン以外の名前解決先
      #- INSECURELDAP=false       #登録ユーザのパスワードに複雑性を強制する(デフォルトtrue)
      #- NOCOMPLEXITY=true        #administratorのパスワードに複雑性を強制する
    cap_add:
        - SYS_ADMIN
    dns_search:
      - example.com               #ドメイン名を指定
    hostname: dc.example.com      #Dockerコンテナのホスト名
    #extra_hosts:
    #  - dc.example.com:192.168.0.15 #これを有効化すると動かないので無指定
    dns:
      - 127.0.0.1                 #自分自身を指定する事！
      - 8.8.8.8
    ports:
      - 192.168.0.15:53:53
      - 192.168.0.15:53:53/udp
      - 192.168.0.15:88:88
      - 192.168.0.15:88:88/udp
      - 192.168.0.15:135:135
      - 192.168.0.15:137-138:137-138/udp
      - 192.168.0.15:139:139
      - 192.168.0.15:389:389
      - 192.168.0.15:389:389/udp
      - 192.168.0.15:445:445
      - 192.168.0.15:464:464
      - 192.168.0.15:464:464/udp
      - 192.168.0.15:636:636
      - 192.168.0.15:1024-1044:1024-1044
      - 192.168.0.15:3268-3269:3268-3269
    privileged: true

